services:
  app:
    container_name: app
    build: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app

    command: sh -c "npm run dev"

    # 標準入力を開く
    stdin_open: true
