import { ServerCookie } from "@/components/cookie/serverCookie";
import StoreProvider from "@/stores/storeProvider";
import { type FC } from "react";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <ServerCookie>
          <StoreProvider>{props.children}</StoreProvider>
        </ServerCookie>
      </body>
    </html>
  );
};

export default RootLayout;
